version: '3.9'

services:
  minecraft_server:
    image: eclipse-temurin:17-jre
    container_name: ${MC_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${MC_BIND_IP}:25565:25565"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .server-data:/usr/data/mc_server:rw
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - frontend
    working_dir: /usr/data/mc_server
    command: ./start

  rsync_backup:
    image: rilegis/rsync:latest
    container_name: ${RS_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .server-data:/usr/data/mc_server:ro
      - .server-backups:/usr/data/backups:rw
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - backend
    working_dir: /usr/data/backups
    command: ./do_backup.sh

# W.I.P --- MAYBE
#  minecraft_overviewer:
#    image: mide/minecraft-overviewer:latest
#    container_name: ${OVERVIEWER_CONTAINER_NAME}
#    restart: unless-stopped
#    volumes:
#      - .server-data:/usr/data/mc_server:ro
#      - .server-render:/usr/data/mc_render:rw
#    environment:
#      - MINECRAFT_VERSION=${MC_VERSION}
#    networks:
#      - backend

volumes:
  server-data:
  server-backups:
#  server-render:

networks:
  frontend:
  backend: