# NextCloud setup
nextcloud:
    command: "Set permissions for volume directory"
        syntax: "docker exec <nextcloud-container-name> chown -R www-data:root /var/www/html"
        comment: ""

    command: "OCC: Set trusted domains"
        syntax: "docker exec --user www-data <nextcloud-container-name> php occ config:system:set trusted_domains 0 --value=<cloud.domain.com>"
        comment: "Increment 'trusted_domains 0' by one each time in case you have multiple domains connected to the same nextcloud instance."
    
    command: "OCC: Set overwrite CLI URL"
        syntax: "docker exec --user www-data <nextcloud-container-name> php occ config:system:set overwrite.cli.url --value=https://<cloud.domain.com>"
        comment: ""

    command: "OCC: Set overwrite protocol"
        syntax: "docker exec --user www-data <nextcloud-container-name> php occ config:system:set overwriteprotocol --value=https"
        comment: ""

    command: "OCC: Set default phone region"
        syntax: "docker exec --user www-data <nextcloud-container-name> php occ config:system:set default_phone_region --value=<country-short-code>"

# ClamAV setup
clamav:
    command: "Set permission for ClamAV socket directory"
        syntax: "docker exec <clamav-container-name> chown -R clamav:clamav /var/run/clamav"
        comment: ""
    
    command: "Set permission for ClamAV virus database"
        syntax: "docker exec <clamav-container-name> chown -R clamav:clamav /var/lib/clamav"
        comment: ""

    command: "Useful tool"
        syntax: "docker exec --interactive --tty <clamav-container-name> clamdtop "/var/run/clamav/clamd.sock""
        comment: "Use this command to execute 'clamdtop' tool."