version: "3.9"
services:
  jellyfin-server:
    image: jellyfin/jellyfin:latest
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - 127.0.0.1:8096:8096
    user: ${PUID}:${PGID}
    network_mode: 'host'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .config:/config
      - .cache:/cache
      - .media:/media

volumes:
  config:
  cache:
  media: